Update CHANGELOG.md
blinkfox/fenix pull request #32
Opened 2020-12-23 09:07 UTC by lize240810

2020-12-23 09:10 UTC, blinkfox requested changes

2020-12-23 09:10 UTC, blinkfox commented on docs/CHANGELOG.md
> -## 🥊 v2.4.0 增强 JPA 的增删改功能 🆕 (2020-20-09)
@lize240810 update to `2020-12-09`.

2020-12-23 09:11 UTC, pengten reviewed
emm，貌似应该是12月

2020-12-26 05:02 UTC, blinkfox commented
这个你后续没再改的话，我就先关掉了哈。我自己改下就行。

2020-12-26 05:02 UTC, closed without merging