自定义SQL中字段_转驼峰
blinkfox/fenix pull request #39
Opened 2021-02-04 06:36 UTC by niejianjun

自定义SQL中字段_转驼峰

2021-02-04 09:09 UTC, pengten commented on src/main/java/com/blinkfox/fenix/jpa/FenixResultTransformer.java
> +            for (int e = 0; e < aliases.length; ++e) {
看逻辑的话，这里 aliases 和 result中的属性，是否顺序必须一致？

2021-02-05 01:12 UTC, niejianjun commented on src/main/java/com/blinkfox/fenix/jpa/FenixResultTransformer.java
> +            for (int e = 0; e < aliases.length; ++e) {
不需要，aliases只是用来缓存bean的属性名称，避免在构建对象时重复的读取属性名称

2021-02-05 01:46 UTC, blinkfox commented
@niejianjun 你还需要多写几个单元测试，我单元测试中使用内存数据库的，你借鉴我的代码写一下。各种情况都要考虑测试下，并且要兼容以前的代码才行

2021-03-02 05:03 UTC, blinkfox requested changes

2022-04-01 03:09 UTC, blinkfox commented
感谢贡献，新版本重写思考和实现了此功能，很抱歉，不能合并你的代码。

2022-04-01 03:09 UTC, closed without merging